spring.application.name=notification-gateway
server.port=8080

# GCP Core Config
spring.cloud.gcp.project-id=homegenie-prod
# Update this path to your actual JSON key file location
spring.cloud.gcp.credentials.location=file:D:/System Design Practical Projects/gcs-signed-url-system/homegenie-prod-97c358d8431e.json

# Custom property for our topic name
notification.topic.name=global-notification-topic

# Cloud Tasks Config (Used by our custom service)
gcp.project-id=homegenie-prod
gcp.location-id=us-central1
gcp.queue-id=notification-queue

# This must be the PUBLIC URL of your app so Google can call it back
notification.gateway.url=https://crumpet-overcoat-hummus.ngrok-free.dev
