spring.application.name=notification-gateway
server.port=8080

# GCP Pub/Sub Config
# Replace with your actual project ID if not detected automatically
# spring.cloud.gcp.project-id=homegenie-prod

# Custom property for our topic name
notification.topic.name=global-notification-topic
