apiVersion: 1

datasources:
  - name: BigQuery
    type: grafana-bigquery-datasource
    access: proxy
    isDefault: true
    jsonData:
      authenticationType: jwt
      defaultProject: homegenie-prod
    secureJsonData:
      # This is now secret-free! It will pull the value from your environment.
      privateKey: ${BIGQUERY_SERVICE_ACCOUNT_JSON}
