server.port=8080

# GCP Configuration
spring.cloud.gcp.storage.bucket-name=tushar-secure-uploads
spring.cloud.gcp.credentials.location=file:D:/System Design Practical Projects/gcs-signed-url-system/homegenie-prod-97c358d8431e.json

# Legacy properties for current code compatibility
gcp.storage.bucket-name=${spring.cloud.gcp.storage.bucket-name}
gcp.storage.credentials-path=${spring.cloud.gcp.credentials.location}
gcp.storage.expiry-minutes=15

# Logging
logging.level.com.example.gcs=DEBUG

# Database Configuration (Google Cloud SQL)
spring.cloud.gcp.sql.database-name=gcs_db
spring.cloud.gcp.sql.instance-connection-name=homegenie-prod:asia-south1:homegenie-db
spring.datasource.username=tushar
spring.datasource.password=iamtus123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
