# Server
server.port=8082

# Elasticsearch Configuration
spring.elasticsearch.uris=http://localhost:9200

# Logging
logging.level.org.springframework.data.elasticsearch.core=DEBUG
logging.level.org.elasticsearch.client=DEBUG
