# Server
server.port=8082

# Elasticsearch Configuration
spring.elasticsearch.uris=http://localhost:9200

# Logging
logging.level.org.springframework.data.elasticsearch.core=DEBUG
logging.level.org.elasticsearch.client=DEBUG
logging.level.com.example.search=DEBUG

# Error details
server.error.include-message=always
server.error.include-exception=true
server.error.include-stacktrace=always
